name: 'Setup Networking Options'
description: 'Set up kernel configuration fragment with required options'
inputs:
  kernel_version:
    description: 'Kernel version (e.g., 6.1)'
    required: true
  android_version:
    description: 'Android version (e.g., android14)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Patch with BBRv3
      if: ${{ inputs.kernel_version == '6.1' && false }}
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common
      run: |
        set -euo pipefail
        curl -L https://raw.githubusercontent.com/ahmed-alnassif/GKI-Duchamp/dev/kernel-patches/bbrv3/bbrv3.patch | patch -p1

    - name: Add IP SET & IPv6_NAT Support
      uses: ./.github/actions/set-kernel-config
      with:
        configs: |
          CONFIG_IP_SET
          CONFIG_IP_SET_MAX=65534
          CONFIG_IP_SET_BITMAP_IP
          CONFIG_IP_SET_BITMAP_IPMAC
          CONFIG_IP_SET_BITMAP_PORT
          CONFIG_IP_SET_HASH_IP
          CONFIG_IP_SET_HASH_IPMARK
          CONFIG_IP_SET_HASH_IPPORT
          CONFIG_IP_SET_HASH_IPPORTIP
          CONFIG_IP_SET_HASH_IPPORTNET
          CONFIG_IP_SET_HASH_IPMAC
          CONFIG_IP_SET_HASH_MAC
          CONFIG_IP_SET_HASH_NETPORTNET
          CONFIG_IP_SET_HASH_NET
          CONFIG_IP_SET_HASH_NETNET
          CONFIG_IP_SET_HASH_NETPORT
          CONFIG_IP_SET_HASH_NETIFACE
          CONFIG_IP_SET_LIST_SET
          CONFIG_NETFILTER_XT_MATCH_ADDRTYPE
          CONFIG_NETFILTER_XT_SET
          CONFIG_NETFILTER_XT_TARGET_LOG
          CONFIG_NETFILTER_XT_MATCH_RECENT
          CONFIG_IP6_NF_NAT
          CONFIG_IP6_NF_TARGET_MASQUERADE

    - name: Apply TCP Congestion Control
      uses: ./.github/actions/set-kernel-config
      with:
        configs: |
          CONFIG_TCP_CONG_ADVANCED
          CONFIG_TCP_CONG_BBR
          CONFIG_TCP_CONG_CUBIC
          CONFIG_TCP_CONG_BIC
          CONFIG_TCP_CONG_WESTWOOD
          CONFIG_TCP_CONG_HTCP
          CONFIG_DEFAULT_BBR
          CONFIG_DEFAULT_TCP_CONG="bbr"
          CONFIG_NET_SCH_FQ
          CONFIG_NET_SCH_FQ_CODEL

    - name: Apply Kernel Config for 5.10
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common
      if: inputs.kernel_version == '5.10'
      run: |
        sed -i 's/CONFIG_IP_SET_MAX/65534/g' net/netfilter/ipset/ip_set_core.c
